# -*- coding: utf-8 -*-

path: "./sample/%date%.txt" 
period:
  day_since: "2013-01-01"
  day_until: "2013-01-31"
  # day_ago: 10

# if you want to insert into gcal, go https://code.google.com/apis/console/
gcal:
  client_id: CLIENT_ID
  client_secret: CLIENT_SECRET
  insert: true

patterns:
  sleep:
    s: 寝[たる]
    e: 起きた
    # if you want to insert into gcal
    calendar: abcdefghijk@group.calendar.google.com
    
  slobbed:
    e: だらだら

  project1:
    e: project1
  
  project2:
    e: project2
  
