# -*- coding: utf-8 -*-

path: "./sample/%date%.txt" 
period:
  day_since: "2013-01-01"
  day_until: "2013-01-31"
  # day_ago: 10

patterns:
  sleep:
    s: 寝[たる]
    e: 起きた
    
  slobbed:
    e: だらだら

  project1:
    e: project1
  
  project2:
    e: project2
  
